/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRewardToken__factory } from "./IRewardToken__factory";
export { NFTStaking__factory } from "./NFTStaking__factory";
