/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as nftStakingSol from "./NFTStaking.sol";
export { KongzNFT__factory } from "./KongzNFT__factory";
export { RewardToken__factory } from "./RewardToken__factory";
